name: Coco Lastico
favicon: null
layout_spectrum: 0.7153677605092525
typography_spectrum: 0.23950395151041448
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.41703615756705403
  lightness: 0.9852717469912022
  saturation: 0.3526985466014594
  rhythmicContrast: 0.30152246356010437
purpose: []
