name: Coco Lastico
favicon: null
layout_spectrum: 0.7153677605092525
typography_spectrum: 0.49664
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#010101'
    - '#a1a5b1'
    - '#c5c9d4'
    - '#494f5d'
    - '#70798a'
  brandStrength: 0.41703615756705403
  lightness: 0.9852717469912022
  saturation: 0.3526985466014594
  rhythmicContrast: 0.30152246356010437
purpose: []
